# Generated by Django 4.0.4 on 2022-06-01 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(default=0)),
                ('saving', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=12)),
                ('no_of_share', models.IntegerField(default=0)),
                ('stock_cc', models.FloatField(default=0)),
                ('total_profit', models.FloatField(default=0)),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userdetails')),
            ],
        ),
    ]
